<Project>
  <PropertyGroup>
    <AssemblyName>PosBuilder</AssemblyName>
    <IntermediateOutputPath>obj/Debug/net8.0-windows/</IntermediateOutputPath>
    <BaseIntermediateOutputPath>obj/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>/app/applet/PosBuilder/obj/</MSBuildProjectExtensionsPath>
    <_TargetAssemblyProjectName>PosBuilder</_TargetAssemblyProjectName>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.5" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/Accessibility.dll" />
    <ReferencePath Include="/root/.nuget/packages/communitytoolkit.mvvm/8.2.2/lib/net6.0/CommunityToolkit.Mvvm.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/Microsoft.CSharp.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.extensions.dependencyinjection.abstractions/8.0.0/lib/net8.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.extensions.logging.abstractions/8.0.0/lib/net8.0/Microsoft.Extensions.Logging.Abstractions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/Microsoft.VisualBasic.Core.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/Microsoft.VisualBasic.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/Microsoft.Win32.Primitives.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/Microsoft.Win32.Registry.AccessControl.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/Microsoft.Win32.Registry.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/Microsoft.Win32.SystemEvents.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/mscorlib.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/netstandard.dll" />
    <ReferencePath Include="/root/.nuget/packages/npgsql/8.0.3/lib/net8.0/Npgsql.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/PresentationCore.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/PresentationFramework.Aero.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/PresentationFramework.Aero2.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/PresentationFramework.AeroLite.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/PresentationFramework.Classic.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/PresentationFramework.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/PresentationFramework.Luna.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/PresentationFramework.Royale.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/PresentationUI.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/ReachFramework.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.AppContext.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Buffers.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.CodeDom.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Collections.Concurrent.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Collections.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Collections.Immutable.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Collections.NonGeneric.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Collections.Specialized.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.ComponentModel.Annotations.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.ComponentModel.DataAnnotations.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.ComponentModel.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.ComponentModel.EventBasedAsync.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.ComponentModel.Primitives.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.ComponentModel.TypeConverter.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Configuration.ConfigurationManager.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Configuration.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Console.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Core.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Data.Common.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Data.DataSetExtensions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Data.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Diagnostics.Contracts.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Diagnostics.Debug.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Diagnostics.DiagnosticSource.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Diagnostics.EventLog.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Diagnostics.FileVersionInfo.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Diagnostics.PerformanceCounter.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Diagnostics.Process.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Diagnostics.StackTrace.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Diagnostics.TextWriterTraceListener.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Diagnostics.Tools.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Diagnostics.TraceSource.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Diagnostics.Tracing.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.DirectoryServices.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Drawing.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Drawing.Primitives.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Dynamic.Runtime.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Formats.Asn1.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Formats.Tar.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Globalization.Calendars.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Globalization.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Globalization.Extensions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.Compression.Brotli.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.Compression.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.Compression.FileSystem.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.Compression.ZipFile.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.FileSystem.AccessControl.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.FileSystem.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.FileSystem.DriveInfo.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.FileSystem.Primitives.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.FileSystem.Watcher.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.IsolatedStorage.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.MemoryMappedFiles.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.IO.Packaging.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.Pipes.AccessControl.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.Pipes.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.IO.UnmanagedMemoryStream.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Linq.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Linq.Expressions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Linq.Parallel.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Linq.Queryable.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Memory.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.Http.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.Http.Json.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.HttpListener.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.Mail.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.NameResolution.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.NetworkInformation.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.Ping.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.Primitives.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.Quic.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.Requests.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.Security.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.ServicePoint.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.Sockets.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.WebClient.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.WebHeaderCollection.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.WebProxy.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.WebSockets.Client.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Net.WebSockets.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Numerics.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Numerics.Vectors.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.ObjectModel.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Printing.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Reflection.DispatchProxy.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Reflection.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Reflection.Emit.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Reflection.Emit.ILGeneration.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Reflection.Emit.Lightweight.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Reflection.Extensions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Reflection.Metadata.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Reflection.Primitives.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Reflection.TypeExtensions.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Resources.Extensions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Resources.Reader.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Resources.ResourceManager.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Resources.Writer.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.CompilerServices.Unsafe.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.CompilerServices.VisualC.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.Extensions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.Handles.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.InteropServices.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.InteropServices.JavaScript.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.InteropServices.RuntimeInformation.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.Intrinsics.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.Loader.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.Numerics.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.Serialization.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.Serialization.Formatters.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.Serialization.Json.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.Serialization.Primitives.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Runtime.Serialization.Xml.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.AccessControl.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Claims.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Cryptography.Algorithms.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Cryptography.Cng.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Cryptography.Csp.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Cryptography.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Cryptography.Encoding.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Cryptography.OpenSsl.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Security.Cryptography.Pkcs.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Cryptography.Primitives.dll" />
    <ReferencePath Include="/root/.nuget/packages/system.security.cryptography.protecteddata/9.0.0/lib/net8.0/System.Security.Cryptography.ProtectedData.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Cryptography.X509Certificates.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Security.Cryptography.Xml.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Security.Permissions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Principal.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.Principal.Windows.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Security.SecureString.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.ServiceModel.Web.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.ServiceProcess.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Text.Encoding.CodePages.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Text.Encoding.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Text.Encoding.Extensions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Text.Encodings.Web.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Text.Json.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Text.RegularExpressions.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Threading.AccessControl.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Threading.Channels.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Threading.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Threading.Overlapped.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Threading.Tasks.Dataflow.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Threading.Tasks.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Threading.Tasks.Extensions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Threading.Tasks.Parallel.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Threading.Thread.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Threading.ThreadPool.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Threading.Timer.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Transactions.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Transactions.Local.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.ValueTuple.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Web.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Web.HttpUtility.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Windows.Controls.Ribbon.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Windows.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Windows.Extensions.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Windows.Input.Manipulations.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Windows.Presentation.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/System.Xaml.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Xml.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Xml.Linq.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Xml.ReaderWriter.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Xml.Serialization.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Xml.XDocument.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Xml.XmlDocument.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Xml.XmlSerializer.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Xml.XPath.dll" />
    <ReferencePath Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/ref/net8.0/System.Xml.XPath.XDocument.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/UIAutomationClient.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/UIAutomationClientSideProviders.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/UIAutomationProvider.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/UIAutomationTypes.dll" />
    <ReferencePath Include="/root/.nuget/packages/microsoft.windowsdesktop.app.ref/8.0.29/ref/net8.0/WindowsBase.dll" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/MainWindow.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/Controls/ColorPickerControl.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/Controls/FileBrowserControl.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/Controls/LoadingOverlay.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/Step1Environment.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/Step2Database.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/Step3Security.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/Step4Branding.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/Step5Users.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/Step6Modules.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/Step7Summary.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/Views/SuccessModal.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/App.g.cs" />
    <Compile Include="/app/applet/PosBuilder/obj/Debug/net8.0-windows/GeneratedInternalTypeHelper.g.cs" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="/tmp/dotnet/sdk/8.0.423/Sdks/Microsoft.NET.Sdk/targets/../analyzers/Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll" />
    <Analyzer Include="/tmp/dotnet/sdk/8.0.423/Sdks/Microsoft.NET.Sdk/targets/../analyzers/Microsoft.CodeAnalysis.NetAnalyzers.dll" />
    <Analyzer Include="/root/.nuget/packages/communitytoolkit.mvvm/8.2.2/analyzers/dotnet/roslyn4.3/cs/CommunityToolkit.Mvvm.CodeFixers.dll" />
    <Analyzer Include="/root/.nuget/packages/communitytoolkit.mvvm/8.2.2/analyzers/dotnet/roslyn4.3/cs/CommunityToolkit.Mvvm.SourceGenerators.dll" />
    <Analyzer Include="/root/.nuget/packages/microsoft.extensions.logging.abstractions/8.0.0/analyzers/dotnet/roslyn4.4/cs/Microsoft.Extensions.Logging.Generators.dll" />
    <Analyzer Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/analyzers/dotnet/cs/Microsoft.Interop.ComInterfaceGenerator.dll" />
    <Analyzer Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/analyzers/dotnet/cs/Microsoft.Interop.JavaScript.JSImportGenerator.dll" />
    <Analyzer Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/analyzers/dotnet/cs/Microsoft.Interop.LibraryImportGenerator.dll" />
    <Analyzer Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/analyzers/dotnet/cs/Microsoft.Interop.SourceGeneration.dll" />
    <Analyzer Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll" />
    <Analyzer Include="/tmp/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.29/analyzers/dotnet/cs/System.Text.RegularExpressions.Generator.dll" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>